export const PROFILES_CREATE_REQUEST="PROFILES_CREATE_REQUEST"
export const PROFILES_CREATE_SUCCESS="PROFILES_CREATE_SUCCESS"
export const PROFILES_CREATE_FAILURE="PROFILES_CREATE_FAILURE"

export const PROFILES_DELETE_REQUEST="PROFILES_DELETE_REQUEST"
export const PROFILES_DELETE_SUCCESS="PROFILES_DELETE_SUCCESS"
export const PROFILES_DELETE_FAILURE="PROFILES_DELETE_FAILURE"

export const GET_ALL_PROFILES_REQUEST="GET_ALL_PROFILES_REQUEST"
export const GET_ALL_PROFILES_SUCCESS="GET_ALL_PROFILES_SUCCESS"
export const GET_ALL_PROFILES_FAILURE="GET_ALL_PROFILES_FAILURE"

